// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ExploreDataBase;

{$R *.RES}
{ITE} {LCID:00000409:00000407} {}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {SetupLocale.dfm}
{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {RCFileType} {ExploreDataBase_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'SetupLocale.dfm' SetupLocaleFrame:TFrame}
{$R 'Unit1.dfm' DataBaseExplorer:TAppletModule}
{$R 'Unit2.dfm' Form2:TForm}
{$R 'ExploreDataBase_DRC.res' 'ExploreDataBase_DRC.rc'}

{$E DEU}

begin
end.